# Using the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference

version: 2.1
orbs:
  python: circleci/python@2
  terraform: circleci/terraform@3.5.0
  snyk: snyk/snyk@2.2.0

jobs:
  pre_commit_lint:
    description: Run pre-commit checks
    resource_class: small
    docker:
      - image: cimg/python:3.11.11
    steps:
      - checkout
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: 1.5.7
      - run:
          command: |
            cp .pre-commit-config.yaml pre-commit-cache-key.txt
            python --version --version >> pre-commit-cache-key.txt
      - restore_cache:
          keys:
            - v1-pre-commit-cache-{{ checksum "pre-commit-cache-key.txt" }}
      - run:
          name: Run pre-commit hook
          command: |
            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
            pip install pre-commit
            pre-commit install
            pre-commit run --all-files
      - save_cache:
          key: v1-pre-commit-cache-{{ checksum "pre-commit-cache-key.txt" }}
          paths:
            - ~/.cache/pre-commit

  validate-terraform:
    description: Validate terraform config
    resource_class: small
    docker:
      - image: cimg/base:2025.01
    steps:
      - checkout
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: 1.5.7
      - run:
          command: make validate-terraform

  security-scan:
    description: Snyk scan for vulnerabilities
    resource_class: small
    docker:
      - image: cimg/base:2025.01
    steps:
      - checkout
      - snyk/scan:
          command: test
          fail-on-issues: true
          severity-threshold: high | critical
          organization: ${SNYK_CICD_ORGANIZATION}
          monitor-on-build: false

workflows:
  build-and-test:
    jobs:
      - pre_commit_lint
      - validate-terraform
      - security-scan
