# Using the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference

version: 2.1
orbs:
  python: circleci/python@2
jobs:
  pre_commit_lint:
    resource_class: small
    docker:
      - image: cimg/python:3.11.11
    steps:
      - checkout

workflows:
  build-and-test:
    jobs:
      - test-python
